name: 'APM - Agent Package Manager'
description: 'Run Agents on Copilot or Codex CLI with agent dependency management and AGENTS.md context compilation'
author: 'danielmeppiel'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  script:
    description: 'Script name from apm.yml to run (default: start)'
    required: false
    default: 'start'
  working-directory:
    description: 'Working directory for execution'
    required: false
    default: '.'
  apm-version:
    description: 'APM version to install (default: latest stable)'
    required: false
    default: 'latest'
  skip-install:
    description: 'Skip automatic MCP dependency installation (default: false)'
    required: false
    default: 'false'
  parameters:
    description: 'JSON object containing parameters to pass to APM (e.g., {"name": "world", "message": "Hello"})'
    required: false
    default: '{}'
  args:
    description: 'Additional CLI arguments for advanced use cases (e.g., "--debug --verbose --custom-flag")'
    required: false
    default: ''

outputs:
  success:
    description: 'Whether execution succeeded (true/false)'
  output:
    description: 'Full execution output from APM'

runs:
  using: 'node20'
  main: 'dist/index.js'
