name: 'AWD - AI Workflow Runner'
description: 'Run AI workflows written in natural language with AWD CLI'
author: 'AWD Team'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  script:
    description: 'Script name from awd.yml to run (default: start)'
    required: false
    default: 'start'
  working-directory:
    description: 'Working directory for execution'
    required: false
    default: '.'
  awd-version:
    description: 'AWD CLI version to install (default: latest stable)'
    required: false
    default: 'latest'
  skip-install:
    description: 'Skip automatic MCP dependency installation (default: false)'
    required: false
    default: 'false'
  parameters:
    description: 'JSON object containing parameters to pass to AWD (e.g., {"name": "world", "message": "Hello"})'
    required: false
    default: '{}'
  args:
    description: 'Additional CLI arguments for advanced use cases (e.g., "--debug --verbose --custom-flag")'
    required: false
    default: ''

outputs:
  success:
    description: 'Whether execution succeeded (true/false)'
  output:
    description: 'Full execution output from AWD'

runs:
  using: 'node20'
  main: 'dist/index.js'
