name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Check build
      run: npm run build

  # Integration test - Test the action itself with hero scenario
  integration-test:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js (for building action)
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
    
    # Test hero scenario - APM audit workflow
    - name: Test - Hero Scenario (Audit)
      uses: ./  # Use the local action code
      with:
        script: audit
        working-directory: examples/test-project
      env:
        GITHUB_COPILOT_PAT: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for testing
    
    # Test basic workflow for backwards compatibility
    - name: Test - Basic Workflow
      uses: ./
      with:
        script: start
        working-directory: examples/test-project
      env:
        GITHUB_COPILOT_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    # Validate end-to-end APM workflow (install -> compile -> run)
    - name: Validate - Complete APM Flow
      run: |
        echo "Verifying APM workflow files were created..."
        cd examples/test-project
        
        # Check that apm.yml exists and has correct structure
        if [[ ! -f "apm.yml" ]]; then
          echo "❌ apm.yml not found"
          exit 1
        fi
        
        # Check that audit workflow prompt exists
        if [[ ! -f "audit-workflow.prompt.md" ]]; then
          echo "❌ audit-workflow.prompt.md not found"
          exit 1
        fi
        
        echo "✅ All required files present for hero scenario"
        echo "✅ Integration tests completed successfully"

  build:
    needs: [test, integration-test]  # Wait for both test and integration-test
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build action
      run: npm run build
    
    - name: Commit build
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git commit -m "Build for release ${{ github.ref_name }}" || exit 0
        git push
