name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Check build
      run: npm run build

  # Integration test - Test the action itself
  integration-test:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      models: read  # Required for GitHub Models API access
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js (for building action)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
    
    # Test hybrid approach - JSON parameters + args (2 birds, 1 stone!)
    - name: Test - Hybrid Parameters
      uses: ./  # Use the local action code
      with:
        script: test-all
        working-directory: examples/test-project
        parameters: |
          {
            "name": "GitHub Actions"
          }
        args: '--debug --verbose'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [test, integration-test]  # Wait for both test and integration-test
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build action
      run: npm run build
    
    - name: Commit build
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git commit -m "Build for release ${{ github.ref_name }}" || exit 0
        git push
